# Generated by Django 5.0.2 on 2024-08-08 19:45

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VideoRequestModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('topic', models.CharField(default='', max_length=500)),
                ('status', models.CharField(default='', max_length=40)),
                ('videourl', models.CharField(max_length=255, null=True)),
                ('imgurl', models.CharField(max_length=255, null=True)),
                ('user', models.CharField(default='', max_length=40)),
                ('ts', models.DateTimeField(auto_now=True)),
                ('seo_checkbox', models.BooleanField(default=False)),
                ('in_depth_checkbox', models.BooleanField(default=False)),
                ('theme', models.CharField(choices=[('descriptive', 'Descriptive'), ('expository', 'Expository'), ('humor', 'Humor'), ('informative', 'Informative'), ('narrative', 'Narrative'), ('persuasive', 'Persuasive')], default='descriptive', max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='VideoResponseModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('video_entries', models.JSONField(default=dict)),
                ('ts', models.DateTimeField(auto_now=True)),
                ('video_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='videos.videorequestmodel')),
            ],
        ),
    ]
