# Generated by Django 5.0.2 on 2024-10-11 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoThemeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='theme_images/')),
            ],
        ),
        migrations.RenameField(
            model_name='videorequestmodel',
            old_name='in_depth_checkbox',
            new_name='long_video',
        ),
        migrations.RemoveField(
            model_name='videorequestmodel',
            name='seo_checkbox',
        ),
        migrations.AlterField(
            model_name='videorequestmodel',
            name='theme',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
