# Generated by Django 5.0.2 on 2024-10-16 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0002_videothememodel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='videorequestmodel',
            name='transcript_url',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='videorequestmodel',
            name='video_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
