# Generated by Django 5.0.2 on 2024-03-22 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogrequestmodel',
            name='blogurl',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
