# Generated by Django 5.0.2 on 2024-04-01 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_blogresponsemodel_blog_entries'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogresponsemodel',
            name='blog_entries',
            field=models.JSONField(default=dict),
        ),
    ]
