# Generated by Django 5.0.2 on 2024-04-08 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_blogresponsemodel_blog_entries'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogrequestmodel',
            name='in_depth_checkbox',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='blogrequestmodel',
            name='seo_checkbox',
            field=models.BooleanField(default=False),
        ),
    ]
