# Generated by Django 5.0.2 on 2024-04-13 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_blogrequestmodel_in_depth_checkbox_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogrequestmodel',
            name='theme',
            field=models.CharField(choices=[('story', 'Story Telling'), ('marketing', 'Marketing'), ('howtoguides', 'How-to-Guides'), ('humor', 'Humor'), ('documentary', 'Documentary')], default='story', max_length=20, null=True),
        ),
    ]
