# Generated by Django 5.0.2 on 2024-04-17 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_blogrequestmodel_theme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogrequestmodel',
            name='theme',
            field=models.CharField(choices=[('descriptive', 'Descriptive'), ('expository', 'Expository'), ('humor', 'Humor'), ('informative', 'Informative'), ('narrative', 'Narrative'), ('persuasive', 'Persuasive')], default='descriptive', max_length=20, null=True),
        ),
    ]
