# Generated by Django 5.0.2 on 2024-04-23 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_alter_blogrequestmodel_theme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogrequestmodel',
            name='topic',
            field=models.CharField(default='', max_length=500),
        ),
    ]
